import { useState } from "react";
import Head from "next/head";
import { LoginForm, RegisterForm } from "@/components";

export default function Home() {
  const [formView, setFormView] = useState<number>(0);

  const handleChildData = (value: number) => {
    console.log(value);
    setFormView(value);
  };

  return (
    <>
      <Head>
        <title>Searcher UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex items-center justify-center h-screen bg-gray-200">
          {formView === 0 ? (
            <LoginForm parentCallback={handleChildData} />
          ) : (
            <RegisterForm parentCallback={handleChildData} />
          )}
        </div>
      </main>
    </>
  );
}
