import Head from "next/head";
import { LoginForm } from "@/components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Searcher UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex items-center justify-center h-screen bg-gray-200">
          <LoginForm />
        </div>
      </main>
    </>
  );
}
